baseurl = "http://blog.enokawa.co/"
languageCode = "ja-jp"
title = "あしたから本気だす"
theme = "angels-ladder"
disqusShortname = "blog-enokawa-co"

[permalinks]
post = "/:year/:month/:day/:filename/"

[Params]
twitter = "https://twitter.com/enkw_"
github = "https://github.com/enokawa"
author = "Naoto Enokawa"
profile = "/images/profile.png"
copyright = "Written by Naoto Enokawa"
analytics = "UA-64780065-1"
