baseurl = "http://enokawa.github.io/"
languageCode = "ja"
title = "あしたから本気だす"
theme = "angels-ladder"

[permalinks]
post = "/:year/:month/:day/:filename/"

[Params]
facebook = "https://facebook.com/naoto.enokawa"
twitter = "https://twitter.com/enkw_"
github = "https://github.com/enokawa"
author = "Naoto Enokawa"
profile = "/images/profile.png"
copyright = "Written by Naoto Enokawa"
analytics = "UA-64780065-1"
